apiVersion: v1
kind: ServiceAccount
metadata:
  name: user
  namespace: public
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: private-pod-access
  namespace: private
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: private-pod-access
  namespace: private
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: private-pod-access
subjects:
- kind: ServiceAccount
  name: user
  namespace: public