apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-user-role
  namespace: private
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  resourceNames:
  - user-secret