---
apiVersion: v1
kind: Namespace
metadata:
  name: public
---
apiVersion: v1
kind: Namespace
metadata:
  name: private
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: user
  namespace: public
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: private-pod-access
  namespace: private
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: private-pod-access
  namespace: private
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: private-pod-access
subjects:
- kind: ServiceAccount
  name: user
  namespace: public
---
apiVersion: v1
kind: Pod
metadata:
  name: public-console
  labels:
    name: public-console
  namespace: public
spec:
  serviceAccountName: user
  containers:
  - name: tools
    image: docker.io/wakeward/ctf:latest
    command: ["sleep", "2d"]
    imagePullPolicy: IfNotPresent
    securityContext:
      allowPrivilegeEscalation: false
---
apiVersion: v1
kind: Pod
metadata:
  name: private-console
  labels:
    name: private-console
  namespace: private
spec:
  containers:
  - name: console
    image: docker.io/wakeward/ctf:latest
    command: ["sleep", "2d"]
    imagePullPolicy: IfNotPresent
    securityContext:
      allowPrivilegeEscalation: false